### ISSUE TITLE
Not so much an issue, a comment

### ISSUE THREAD

**Issue by esacs2004** [DJMOC/KOWbot#2]
Just an FYI, `pygetwindow ` module can be used to procure the active window, simply have them click the window they want to use and you can then grab top_left and bottom_left automatically without the manual effort.

Example:
```
while keyboard.is_pressed('enter') == False and keyboard.is_pressed('space') == False:
    for item in pygetwindow.getAllWindows():
        if item.isActive():
            box = Screen.makeBox(
                [item.topleft.x, item.topleft.y],
                [item.bottomright.x, item.bottomright.y]
            )
            print(f'you chose {item.title} at {box}')
    sleep(.5)
```

**Comment by DJMOC** [comment]
I was searching for something like that! Please do some test in branche V0.21.10B

**Comment by DJMOC** [comment]
![image](https://user-images.githubusercontent.com/44927761/139792346-96ba468b-5b94-476a-b68d-bbfd926d212a.png)

code will be updated when I have time but for single instance I can find the right play area within 1 pxl

**Comment by DJMOC** [comment]
Integrated it in dev code. Had to fix some modules issues first but now it work on my side. I'll push the new code when I'm done with all parts.
