### ISSUE TITLE
torch issue

### ISSUE THREAD

**Issue by BuzzKillPB** [DJMOC/KOWbot#6]
This is likely because I am a complete noob with python considering how long it has been since I used it, but I got the following error when installing requirements.txt:

ERROR: Could not find a version that satisfies the requirement torch==1.10.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.10.0

**Comment by DJMOC** [comment]
This is most likely to be your python version being incompatible.
open a command prompt and enter the following command : py --version
make sure it is in the format Python 3.7.x, if it's not you have to download version 3.7 and install it : https://www.python.org/downloads/release/python-370/

**Comment by BuzzKillPB** [comment]
I uninstalled python (mine was 3.10) and installed 3.7.9. I got 1 error and 1 warning:

ERROR: imageio 2.10.1 has requirement pillow>=8.3.2, but you'll have pillow 8.2.0 which is incompatible.

WARNING: You are using pip version 20.1.1; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\buzzy\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.

**Comment by DJMOC** [comment]
the warning is irrelevant to your problems, but is would not be bad to execute the command they provided : py -m pip install --upgrade pip

For the error, I have the feeling you have other projects requiring different versions of imageio. Did you installed directly in main environment or you are using virtual ones?

I can recommend this page to help you start with virtual environments : 
https://docs.python.org/3/library/venv.html#module-venv

**Comment by DJMOC** [comment]
Hi, is the proposed solution fixed your issue?

**Comment by BuzzKillPB** [comment]
It did. I just haven't had the time to do anything with it as yet.

**Comment by DJMOC** [comment]
Good, I'll update the readme file accordingly then.
